### ISSUE TITLE
Extraneous dependency: `request-promise-native`

### ISSUE THREAD

**Issue by mvandervliet** [banzaicloud/node-service-tools#1]
## Overview of the Issue

This package includes a reference to the **very sizable** `request-promise-native` package under `dependencies` [here](https://github.com/banzaicloud/node-service-tools/blob/master/package.json#L71), and is implemented as part of `makeRequest` helper function. 

👉 [![install size](https://packagephobia.now.sh/badge?p=request-promise-native)](https://packagephobia.now.sh/result?p=request-promise-native)

The exported `makeRequest` helper function is not officially documented, and appears to be utilized only within unit test scripts.

## Reproduce the Error

```text
npm install
npm ls --prod | grep request-promise-native
```

## Related Issues

N/A

## Suggest a Fix

Without specific knowledge of the project roadmap for exposing such `http` helper functions, it may be worthwhile either installing under `devDependencies` or refactoring to use a more lightweight HTTP request package:

- https://www.npmjs.com/package/got
- https://www.npmjs.com/package/axios
- https://www.npmjs.com/package/node-fetch

**Comment by tothandras** [comment]
@mvandervliet you are totally right, I was exposing it to be used in [other projects](https://github.com/spotguides/nodejs-mongodb), but it shouldn't be a required dependency. Please review #2 if you have some time! Thank you!
