### ISSUE TITLE
pino default level not found

### ISSUE THREAD

**Issue by orefalo** [banzaicloud/node-service-tools#5]
Thanks for this great library.

Weird, I am getting this error

```
    throw Error(`default level:${defaultLevel} must be included in custom levels`)
          ^
Error: default level:undefined must be included in custom levels
```

I've got in my .env

```
LOGGER_LEVEL=debug
LOGGER_REDACT_FIELDS=password, pass, authorization, auth, cookie, _object

```

Thanks

**Comment by orefalo** [comment]
this I found the issue-

I find the config part of the library is messy and error prone

**Comment by tothandras** [comment]
Thank you for reporting your issue! It seems like a bug, when `NODE_ENV` is not set there is no default log level. In the PR (#7) I've also removed the .env handling altogether as it was more confusing than useful.

**Comment by tothandras** [comment]
The fix is released as version `3.0.0-beta.1`:
```bash
npm i @banzaicloud/service-tools@3.0.0-beta.1
```

**Comment by orefalo** [comment]
thanks a bunch!   Agreed, it was confusing ;-)

**Comment by orefalo** [comment]
PS: removing the default env handling is most welcome ;-) tks
